export const createTables = [
  `
	DROP TABLE "users";
	DROP TABLE "activity";
	DROP TABLE "os";
	DROP TABLE "os_activity";
	DROP TABLE "os_activity_photo";
	
CREATE TABLE "users" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"email" VARCHAR(50) NOT NULL,
	"password" VARCHAR(255) NOT NULL,
	"photo" VARCHAR(255) DEFAULT NULL,
	"role" VARCHAR(30) NOT NULL,
	"status" VARCHAR(30) NOT NULL,
	"recovery_password" BOOLEAN DEFAULT FALSE,
	PRIMARY KEY("id")
);

CREATE TABLE "activity" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"category" VARCHAR(50) DEFAULT NULL,
	"sub_category" VARCHAR(50) DEFAULT NULL,
	"description" VARCHAR(255) NOT NULL,
	"status" VARCHAR(30) NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE "os" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"localization_name" VARCHAR(255) NOT NULL,
	"localization" VARCHAR(255) NOT NULL,
	"coordinates" JSON DEFAULT NULL,
	"status" VARCHAR(30) NOT NULL,
	"date_created" DATE NOT NULL,
	"date_finished" DATE DEFAULT NULL,
	"description" VARCHAR(255) DEFAULT NULL,
	"comment" VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE "os_activity" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"os_id" INTEGER NOT NULL,
	"activity_id" INTEGER NOT NULL,
	"comment" VARCHAR(255) DEFAULT NULL,
	"status" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE "os_activity_photo" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"os_id" INTEGER NOT NULL,
	"activity_id" INTEGER NOT NULL,
	"index" INTEGER NOT NULL,
	"type" VARCHAR(20) NOT NULL,
	"file" VARCHAR(255) NOT NULL,
	"size" VARCHAR(20) NOT NULL,
	"status" VARCHAR(30) NOT NULL,
	"client_check" VARCHAR(20) DEFAULT NULL,
	PRIMARY KEY("id")
);
`,
];

export const registers = [
  `
INSERT INTO "os" (user_id, localization_name, localization, coordinates, status, date_created, description, comment)
VALUES
(1, 'Escritório Central', 'Av. Paulista, 1000 - São Paulo/SP', '{"lat": "-23.561684", "lng": "-46.655981"}', 'Aberto', '2025-09-01', 'Troca de cabeamento de rede', 'Aguardando técnico'),
(2, 'Fábrica Zona Norte', 'Rua das Indústrias, 250 - São Paulo/SP', '{"lat": -23.472084, "lng": -46.633178}', 'Em andamento','2025-09-02',  'Manutenção em máquina de corte', 'Cliente solicitou urgência'),
(3, 'Loja Shopping Center', 'Av. das Nações, 400 - São Paulo/SP', '{"lat": -23.609512, "lng": -46.697210}', 'Concluído', '2025-09-03', 'Instalação de ar condicionado', 'Serviço finalizado com sucesso');


-- =======================
-- ATIVIDADES
-- =======================
INSERT INTO "activity" (name, category, sub_category, description, status)
VALUES
('Inspeção inicial', 'Civil', 'Estrutura', 'Verificação dos cabos atuais', 'Ativo'),
('Troca de cabos', 'Eletrica', 'Substituição', 'Cabos antigos substituídos por novos', 'Ativo'),
('Parada da máquina', 'Elétrica', 'Equipamentos', 'Desligamento seguro para manutenção', 'Ativo'),
('Troca de rolamentos', 'Elétrica', 'Equipamentos', 'Peças novas instaladas no eixo principal', 'Ativo'),
('Instalação unidade interna', 'Elétrica', 'Instalação', 'Unidade interna instalada e testada', 'Ativo'),
('Instalação unidade externa', 'Elétrica', 'Instalação', 'Unidade externa instalada no telhado', 'Desativado');


-- =======================
-- ATIVIDADES DA OS
-- =======================
INSERT INTO "os_activity" (os_id, activity_id, status)
VALUES
(1, 1, 'Aberto'),
(1, 2, 'Aberto'),
(1, 3, 'Aberto'),
(1, 4, 'Aberto'),
(2, 6, 'Aberto'),
(2, 4, 'Aberto'),
(3, 1, 'Aberto'),
(3, 2, 'Aberto'),
(3, 5, 'Aberto'),
(3, 6, 'Aberto');


-- =======================
-- FOTOS DAS ATIVIDADES
-- =======================
INSERT INTO "os_activity_photo" (os_id, activity_id, index, type, file, size, status, client_check)
VALUES
(1, 1, 0, 'before', 'foto_inspecao_cabos.jpg', '1.2MB', 'Ativo', 'Aprovado'),
(1, 2, 1, 'before', 'foto_troca_cabos.jpg', '2.1MB', 'Ativo', 'Pendente'),
(2, 3, 2, 'after', 'foto_parada_maquina.jpg', '850KB', 'Ativo', 'Aprovado'),
(2, 4, 0, 'after', 'foto_troca_rolamentos.jpg', '1.5MB', 'Ativo', 'Aprovado'),
(3, 5, 1, 'after', 'foto_instalacao_interna_ar.jpg', '1.8MB', 'Ativo', 'Aprovado'),
(3, 6, 2, 'before', 'foto_instalacao_externa_ar.jpg', '2.4MB', 'Ativo', 'Aprovado');

`,
];
// "activity_id" INTEGER NOT NULL,
// "type" VARCHAR(20) NOT NULL,
