export const createTables = [
  `CREATE TABLE "os" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"localization_name" VARCHAR(255) NOT NULL,
	"localization" VARCHAR(255) NOT NULL,
	"coordinates" JSON,
	"date" DATE NOT NULL,
	"status" VARCHAR(255) NOT NULL,
	"description" VARCHAR(255) DEFAULT NULL,
	"comment" VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE "os_activity" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"os_id" INTEGER NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"comment" VARCHAR(255) DEFAULT NULL,
	"status" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE "os_activity_photo" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"os_id" INTEGER NOT NULL,
	"activity_id" INTEGER NOT NULL,
	"index" INTEGER NOT NULL,
	"type" VARCHAR(20) NOT NULL,
	"file" VARCHAR(255) NOT NULL,
	"size" VARCHAR(20) NOT NULL,
	"status" VARCHAR(20) NOT NULL,
	"client_check" VARCHAR(20) DEFAULT NULL,
	PRIMARY KEY("id")
);
`,
];

export const registers = [
	`
INSERT INTO "os" (user_id, localization_name, localization, coordinates, date, status, description, comment)
VALUES
(1, 'Escritório Central', 'Av. Paulista, 1000 - São Paulo/SP', '{"lat": -23.561684, "lng": -46.655981}', '2025-09-01', 'Aberto', 'Troca de cabeamento de rede', 'Aguardando técnico'),
(2, 'Fábrica Zona Norte', 'Rua das Indústrias, 250 - São Paulo/SP', '{"lat": -23.472084, "lng": -46.633178}', '2025-09-02', 'Em andamento', 'Manutenção em máquina de corte', 'Cliente solicitou urgência'),
(3, 'Loja Shopping Center', 'Av. das Nações, 400 - São Paulo/SP', '{"lat": -23.609512, "lng": -46.697210}', '2025-09-03', 'Concluído', 'Instalação de ar condicionado', 'Serviço finalizado com sucesso');


-- =======================
-- ATIVIDADES DA OS
-- =======================
INSERT INTO "os_activity" (os_id, name, comment, status)
VALUES
(1, 'Inspeção inicial', 'Verificação dos cabos atuais', 'Concluído'),
(1, 'Troca de cabos', 'Cabos antigos substituídos por novos', 'Em andamento'),
(2, 'Parada da máquina', 'Desligamento seguro para manutenção', 'Concluído'),
(2, 'Troca de rolamentos', 'Peças novas instaladas no eixo principal', 'Em andamento'),
(3, 'Instalação unidade interna', 'Unidade interna instalada e testada', 'Concluído'),
(3, 'Instalação unidade externa', 'Unidade externa instalada no telhado', 'Concluído');


-- =======================
-- FOTOS DAS ATIVIDADES
-- =======================
INSERT INTO "os_activity_photo" (os_id, activity_id, index, file, size, status, client_check)
VALUES
(1, 1, 0, 'foto_inspecao_cabos.jpg', '1.2MB', 'Ativo', 'Aprovado'),
(1, 2, 1, 'foto_troca_cabos.jpg', '2.1MB', 'Ativo', 'Pendente'),
(2, 3, 2, 'foto_parada_maquina.jpg', '850KB', 'Ativo', 'Aprovado'),
(2, 4, 0, 'foto_troca_rolamentos.jpg', '1.5MB', 'Ativo', 'Aprovado'),
(3, 5, 1, 'foto_instalacao_interna_ar.jpg', '1.8MB', 'Ativo', 'Aprovado'),
(3, 6, 2, 'foto_instalacao_externa_ar.jpg', '2.4MB', 'Ativo', 'Aprovado');

`,
];
